remove deprecated allow-external option

diff --git a/bin/pipupgrade b/bin/pipupgrade
--- a/bin/pipupgrade
+++ b/bin/pipupgrade
@@ -27,7 +27,7 @@ tmpfile=`mktemp --suffix .pip`
 # \param $1: name of the pip code to use
 # \return: list of packages to be upgraded
 function get_toupdate(){
-  $1 list -l -o --allow-all-external 2>/dev/null >$tmpfile
+  $1 list -l -o 2>/dev/null >$tmpfile
   if [ $? -eq 0 ]
   then
     to_up=`awk '{print $1}' $tmpfile`
@@ -37,7 +37,7 @@ function get_toupdate(){
 
     echo $to_up
   else
-    >&2 echo -e "\e[1;31m'`which pip` list -l -o --allow-all-external' failed with error $?.\e[0m"
+    >&2 echo -e "\e[1;31m'$1 list -l -o' failed with error $?.\e[0m"
     echo ""
   fi
 }
@@ -77,7 +77,7 @@ function update_local(){
   if [ $is_l = true ]
   then
     echo $2
-    $1 install -U --user --allow-all-external $2 >> $3
+    $1 install -U --user $2 >> $3
     checkexit $? $2
   else
     echo To upgrade $2 first re-install it by hand using --user
@@ -90,7 +90,7 @@ function update_local(){
 # \param $3: log file name
 function update_venv(){
   echo $2
-  $1 install -U --allow-all-external $2 >> $3
+  $1 install -U $2 >> $3
   checkexit $? $2
 }
 
